console.log("\"Hello Refocus !!\"");
// console.log("~");
// console.log("\"I am gonna be an awesome web developer.\"");
// console.log("~");
// console.log("\"PLAY to your STRENGHTS!\"");
// console.log("~");
// console.log("\u25CF Know your Aptitude");
// console.log("\u25CF Recognize Patterns of Failure");
// console.log("\u25CF Optimise your Operation");
// console.log("\u25CF Practice and Patience");
// console.log("\u25CF Go Beyond Good Enough");
// console.log("~");